### ISSUE TITLE
Als gebruiker wil ik de mutatieregels beter begrijpen als statusmeldingen omdat ze nu wat onoverzichtelijk zijn

### ISSUE THREAD

**Issue by peterboer** [forza-mor-rotterdam/profilr#105]
Maak voorstel voor weergave van mutatieregels meer als stappen/procesje waarbij zaken als datum en 'status' beter in beeld komen dan nu. Kijk wellicht ook naar de plaatsing ervan op de pagina (belangrijkheid mag wat beter).

- [x] UX
- [ ] Front-end

**Comment by Wouterboer** [comment]
Ik heb een nieuwe opzet gemaakt waarbij de mutatieregels wat meer als tijdlijn worden weergegeven: https://www.figma.com/file/79rTNGxSHrSxCnKCUaYWJV/Meldingen-Openbare-Ruimte?node-id=1810%3A34088&t=OmMxtierys0O1pW0-1

**Comment by peterboer** [comment]
ah; dat ziet er een stuk overzichtelijker uit. @Wouterboer wat is die 'externe' referentie?

**Comment by Wouterboer** [comment]
Hmm, ik zag dat veld vanochtend nog maar ik kan nu geen enkele melding meer vinden waar het bijstaat. Misschien maar niet overnemen en testen of gebruikers het missen?
