### ISSUE TITLE
Als gebruiker wil ik ineens alle filters verwijderen, omdat ik ze nu per stuk moet verwijderen en dat lang duurt!

### ISSUE THREAD

**Issue by peterboer** [forza-mor-rotterdam/profilr#149]
Dus naast het kruisje van verwijderen wat per filter, ook graag een 'verwijder alle' toevoegen bij gekozen filters.

**Comment by Wouterboer** [comment]
Zie [Figma](https://www.figma.com/file/79rTNGxSHrSxCnKCUaYWJV/Meldingen-Openbare-Ruimte?node-id=766%3A11227&t=dLw9JSeporAEpV2G-1)

- Het linkje hoeft alleen getoond te worden als er minimaal 1 filter actief is
- Als de gebruiker op het linkje tapt kan het blokje 'Actieve filters' worden gesloten. De filters worden nog wel getoond.
